version: "3"
services:
  
  # ui:
  #  build:
  #     context: ./ui
  #     dockerfile: Dockerfile.dev
  #  ports:
  #   -  3000:3000
  #  networks:
  #   -  mean-stack-net
  #  volumes:
  #   -  ./ui/src:/usr/app/src
  #   -  ./ui/public:/usr/app/public
  #  depends_on:
  #   - api
  #  stdin_open: true
  #  tty: true

  api:
    build:
       context: ./api
       dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./api:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3080:3080
    depends_on:
      - postgres
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 12345
      DB_NAME: audible
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=audible
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

# networks:
#   mean-stack-net:
#     driver: bridge

volumes:
  db:
    driver: local